### ISSUE TITLE
How about ubuntu in oc

### ISSUE THREAD

**Issue by Zereker** [iGuan7u/OpenCore-Gigabyte-Z390M-Gaming#1]

**Comment by iGuan7u** [comment]
Sorry about that, ubuntu is not my purpose to make this repository, and I have never test on it.
Maybe Opencore is not the best choice for ubuntu, you should try it by yourself.

**Comment by Zereker** [comment]
> Sorry about that, ubuntu is not my purpose to make this repository, and I have never test on it.
> Maybe Opencore is not the best choice for ubuntu, you should try it by yourself.

Thank you.
